### ISSUE TITLE
Build select images using arm64 archicecture

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#104]
Currently our images are all built for amd64 which works fine for production. But for local development, folks on Apple Silicon may want to build previews from our branches on the https://github.com/TugboatQA/tugboat-test/ repository. We should build arm64 for whatever images those branches use. I believe we are already using buildx, so shouldn't be too tricky there, but we will potentially need some not insignificant refactoring to our makefile / scripts.

**Comment by deviantintegral** [comment]
I am already building PHP images locally as a part of https://github.com/TugboatQA/images/pull/102 for ARM. Those seem to work fine.

The biggest issue is if upstream images are using different names for different architectures. I actually don't think there's too much work to do here, unless we want to actually push ARM images up to docker hub or GHCR.

**Comment by q0rban** [comment]
For building previews on local development installations of Tugboat on Apple silicon, we do need to push them up to docker hub. Otherwise, folks would manually need to build and tag the images locally prior to being able to build a preview on their local Tugboat installation.
