### ISSUE TITLE
Redis 7 throws a WARNING about memory overcommit needing to be enabled.

### ISSUE THREAD

**Issue by apotek** [TugboatQA/images#143]
When using `redis:7`, the following warning is thrown.

> 9:C 28 Sep 2024 02:41:28.955 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
M9:C 28 Sep 2024 02:41:28.956 * oO0OoO0OoO0Oo Redis is sta

This is our configuration:
```
  redis:
    image: 'tugboatqa/redis:7'
```

It is rare, in a CMS like Drupal to worry about background saves or replication with regards to Redis data, since it is used as a volatile cache layer. 

However, some people may be using Redis as a non-volatile, semi-permanent or permanent data store, so it seems like this is something that should perhaps be configured by default. 

```
RUN echo 'vm.overcommit_memory = 1' >> /etc/sysctl.conf && \
sysctl vm.overcommit_memory=1
```

I can make a pull request, but wanted to gather feedback first before testing anything.

**Comment by q0rban** [comment]
Thank you @apotek ! Right now, we have a single Dockerfile for [all versions of redis we currently support](https://github.com/TugboatQA/dockerfiles/blob/f330094e9eaebef456d8e21a9ee2cf3c241e0e38/redis/TAGS.md). Do you know if this change will work on all versions? (Perhaps the easiest way to test this is with a PR, we can then run our GHA workflow to test it.

**Comment by q0rban** [comment]
Based on [this](https://github.com/redis/docker-library-redis/issues/298) it sounds like this isn't a change we can make in the dockerfile, but rather needs to be made on the host. If you would like us to make this change on the Chromatic server, let us know. :)
