### ISSUE TITLE
CentOS is EOL: remove and replace with redhat/ubi images

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#147]
As of docker-library/official-images#17094, there is now no official docker image for CentOS.

- [x] Remove centos from our repo
- [x] Check if any customers are using tugboatqa/centos and let them know it's going away
- [x] Remove tugboatqa/centos from docker hub
- [x] Remove documentation about centos from https://docs.tugboatqa.com/reference/tugboat-images/
- [x] Add replacement

**Comment by rabbitlair** [comment]
According to [official announcement](https://www.redhat.com/en/topics/linux/centos-linux-eol#migration-options), the only recommendation is to migrate to RHEL. I would remove CentOS entirely after some reasonable time - it is officially EOL, and this period of grace should not be too long.

**Comment by q0rban** [comment]
@rabbitlair they have already removed the centos official docker image that we are extending, so our builds are currently failing. So we do need to do _something_.

**Comment by rabbitlair** [comment]
@q0rban, noted! Thank you for the heads up about the image being removed.

I have create PR #148 to remove the Centos7 image. Also, we may consider adding the official `rhel` images from [Dockerhub](https://hub.docker.com/u/redhat). Any thoughts?

**Comment by q0rban** [comment]
Perhaps https://hub.docker.com/r/redhat/ubi9?

**Comment by q0rban** [comment]
Ah, that's what you linked to as well. 👍

**Comment by rabbitlair** [comment]
Sounds good to me. I will add that one in a follow up pull request, so we can merge #148 as soon as possible to prevent our builds from erroring

**Comment by q0rban** [comment]
Updated the issue description with some tasks

**Comment by q0rban** [comment]
After checking, and some conversation, since no one is currently using a centos image, we don't feel the need to create a new `rhel/ubi*` image for tugboat. If someone requests one, we can add it at that point.
