### ISSUE TITLE
Install opcache extension on appropriate PHP images

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#21]
Versions of PHP that have opcache should have the extension enabled. Drupal outputs a warning if it's not enabled. 

`docker-php-ext-install opcache`

**Comment by apotek** [comment]
Unfortunately `docker-php-ext-install` will recompile & install the extension whether it is already installed or not. 

It would be less expensive to:

```sh
opcache=$(php -i | awk '/opcache\.enable / { print $5 }')
if [ -z "$opcache" ]; then
  docker-php-ext-install opcache
  docker-php-ext-enable opcache
elif [ "$opcache" = "Off" ];then
 docker-php-ext-enable opcache
if 
```

Happy to contribute again if you would like.

**Comment by apotek** [comment]
Looking more closely at the upstream php images it seems no php extensions are added outside what ships with the default PHP. So, yes, `docker-php-ext-install opcache` seems to be all that is needed.
