### ISSUE TITLE
Shut down services gracefully

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#44]
Apparently [different processes expect different signals sent](https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/), but Docker defaults to SIGTERM. Also, it appears that this is only sent to the entrypoint / cmd, and not to any other running processes (I haven't seen any official documentation about this, just rumblings on the internet). It also appears that runit exits immediately if given a SIGTERM. http://smarden.org/runit/runsvdir.8.html

## To replicate:

```
docker run -d --name=mariadbtest tugboatqa/mariadb:latest
docker logs mariadbtest
# Rerun the above until you see mysqld: ready for connections
docker stop mariadbtest
docker logs mariadbtest
# Note that no shutdown has occurred.
docker start mariadbtest
# Note that MySQL goes into disaster recovery mode and has to rebuild the ibd files which on large databases, can take a while.
```

## An ugly fix
A prototype that fixes the above issue. NOTE: I'm not necessarily recommending this as a solution, but I tried things like `tini` and sending a different signal with `STOPSIGNAL SIGHUP` and wrapping in a trap among others, and this at least _works_ in my testing as a way to shut down mysql gracefully.

`boot`
```sh
#!/bin/bash

# Adapted from https://github.com/discourse/discourse_docker/blob/master/image/base/boot
# We use this to boot up as runit doesn't handle TERM and will not wait to exit when done
# Further reading:
# - https://hynek.me/articles/docker-signals/
# - https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
shutdown() {
  echo "Shutting Down..."
  find /etc/service -mindepth 1 -maxdepth 1 -type d -printf '%f\0' | xargs -0 sv force-stop
  kill -HUP $RUNSVDIR
  wait $RUNSVDIR

  # give stuff a bit of time to finish
  sleep .1

  ORPHANS=`ps -eo pid | grep -Eo '[0-9]+' | grep -v '^1$'`
  SHELL=/bin/bash echo "$ORPHANS" | xargs -I {} sh -c 'timeout 5 /bin/bash -c "kill {} && wait {}" || kill -9 {}' 2> /dev/null
  exit
}

/usr/bin/runsvdir -P /etc/service &
RUNSVDIR=$!
echo "Started runsvdir, PID is $RUNSVDIR"
trap shutdown SIGTERM SIGHUP
wait $RUNSVDIR

shutdown
```

`Dockerfile`
```dockerfile
FROM tugboatqa/mariadb
COPY boot /sbin/boot
CMD [ "/sbin/boot" ]
```

```
docker build . -t localhost:5000/mariadbtest:latest
docker run -d --name=mariadbtest2 localhost:5000/mariadbtest:latest
docker logs mariadbtest2
docker stop mariadbtest2
docker logs mariadbtest2
# Note here that a mysql shutdown _has_ occurred.
```

## Further reading
- https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
- https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/
- https://peter.bourgon.org/blog/2015/09/24/docker-runit-and-graceful-termination.html
- https://github.com/peterbourgon/runsvinit/issues/3

**Comment by juampynr** [comment]
@q0rban I haven't faced or just did not notice this issue. Nice sleuthing!

**Comment by q0rban** [comment]
This looks interesting / promising: https://github.com/Yelp/dumb-init

**Comment by q0rban** [comment]
This is interesting, I hadn't noticed this before:

> If your process falls into this category, you can use the --init option when you run the container. The --init flag inserts a tiny init-process into the container as the main process, and handles reaping of all processes when the container exits.

https://docs.docker.com/config/containers/multi-service_container/

**Comment by apotek** [comment]
Can we steal an idea from very very old mysql distributions where the server was started and stopped via mysql_safe (or safe_mysqld) script and the script essentially handled the signaling? So a sigterm goes to the wrapper script and it makes sure to shut down the background process it started. So this would essentially mean modifying entrypoint to do something similar, 

https://github.com/MariaDB/mariadb-docker/blob/51c2b915a19573f233424635627355bcf14057d4/11.1/docker-entrypoint.sh#L617

```
	exec "$@"
```

to

```
      exec mywrapper "$@"
```

Would that help here?

**Comment by sean-e-dietrich** [comment]
One thing I have done is use supervisord as the main service for running multiple services.
