### ISSUE TITLE
Offer alpine variation of Node

### ISSUE THREAD

**Issue by bpatram** [TugboatQA/images#55]
I would love if the official tugboat Node docker image offered an Alpine linux variation as well. The official Node images offer this (https://hub.docker.com/_/node?tab=tags&page=1&name=alpine). 

Using Alpine linux instead of Debian would drastically reduce image size. Currently when spinning up a basic node application it consumes almost the entire 2gb storage allotment my account is given!

**Comment by q0rban** [comment]
Ben, thoughts on this?

**Comment by q0rban** [comment]
@bpatram we're going to work on some documentation on the rationale!

**Comment by q0rban** [comment]
I'm closing this in favor of TugboatQA/docs#162.
