### ISSUE TITLE
Postgres image is not starting up on Tugboat

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#58]
When using the Postgres image, a customer noted that the builds would fail with a `Timeout waiting for container to start` error. Looking in the service logs, the following error was displayed:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.
       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by stemount** [comment]
@q0rban thanks for your support.
**Slack thread for background/additional info: https://tugboatqa.slack.com/archives/C0ZCJHW2F/p1593346430183300**

To note:
- setting the postgres password was not really the outcome but simply set the variables as  per muscle memory when using postgres' official docker image.

```yaml
services:
  postgres:
    image: tugboatqa/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
```

This POSTGRES_PASSWORD set in environment variables seemed to result in

> Error: Database is uninitialized and superuser password is not specified.
>        You must specify POSTGRES_PASSWORD to a non-empty value for the
>        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

however, when `POSTGRES_PASSWORD` is set using the Tugboat UI therefore overriding what is in the `.tugboat/config.yml` the pg instance will start no problemos!

**Comment by bchavet** [comment]
Looks like the upstream image changed $POSTGRES_PASSWORD from optional to required a few months ago.

https://github.com/docker-library/docs/commit/2e59fc9a6aee9125eac1a29283205333da4760fa

I'm working on rebuilding our images to include a default password.

**Comment by stemount** [comment]
good spot @bchavet I'll guess for the record if anybody finds this github issue and needs PostgreSQL **IMMEDIATELY** then all you need to do is set `POSTGRES_PASSWORD` env variable for now ;)

**Comment by bchavet** [comment]
New images have been pushed to dockerhub with $POSTGRESS_PASSWORD prepopulated.
