### ISSUE TITLE
Disable bin_log on MySQL/MariaDB images

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/images#85]
_Originally created by @quicksketch at Lullabot/tugboat#4666._

---

**Is your feature request related to a problem? Please describe.**

Trying to fit a site into Tugboat's free plan can be difficult with PHP + MySQL images running around 1.2 GB before even loading any content. When importing a moderately sized database, the mysql container gets substantially larger. One part of this is that the binary logs used for database recovery and synchronization seem to be getting written when doing the initial mysql import. Disabling this would save a fair amount of space on all Tugboat accounts.

**Describe the solution you'd like**
Modify the default `/etc/mysql/conf.d/tugboat.cnf` to [disable bin_log](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#option_mysqld_log-bin) with the following line:
```
disable_log_bin
```

**Describe alternatives you've considered**

In my testing, I could not figure out how to change this setting because ~there is no way to restart MySQL within a container; you must [restart the entire container](https://stackoverflow.com/questions/52993172/how-to-restart-mysql-service-from-mysql-docker-container), which I don't have permission to do on Tugboat.~ Correction: it is possible to restart mysql in Tugboat with `sv restart mysql`.

For example I tried this:
```
- echo "disable_log_bin" >> /etc/mysql/conf.d/tugboat.cnf
```

But I need to restart MySQL for it to take effect. Trying options like `mysqld restart` gives errors that it cannot be run as root, and all documentation I could find suggests you must restart the container.

**Additional context**
I found I can accomplish this manually by disabling bin log during the mysql import only. And separately I found that it's valuable to save disk space by not saving the mysql archive locally during the build step, instead pipe it directly into mysql. This is the most space-efficient command I could come up with:

```
ssh root@example.com 'cat ~/database.sql.gz' | zcat | mysql --init-command="SET SQL_LOG_BIN = 0;" tugboat
```

To verify the difference in bin logs, start up a mysql image and check the contents of the `/var/lib/mysql` directory:

```
ls -lah /var/lib/mysql/binlog*
```

Try this before and after importing a database, and you'll see the binlog files grow substantially; at least the size of the uncompressed database.

**Comment by q0rban** [comment]
Most of the docs seem to suggest that it should be `skip-log-bin` in the my.cnf, except in MySQL 8+ where the `disable-log-bin` was added as well. I can't find anything definitive to say this, but since we create tags for older versions as well, I'm going to stick with the `skip-log-bin` and see if that works on all of these.

**Comment by q0rban** [comment]
Confirmed that `skip-log-bin` works on both mysql and mariadb.

**Comment by quicksketch** [comment]
Super, that sounds right to me as well.
